### ISSUE TITLE
Asset licenses?

### ISSUE THREAD

**Issue by kozross** [MattSurabian/DuckHunt-JS#13]
Are your assets licensed the same way as your code, or differently?

**Comment by MattSurabian** [comment]
That's a bit of a gray area since they aren't really mine to license. 

It's my understanding that Nintendo is not interested in pursuing legal action against fans and makers which utilize their assets in derivative works. This was announced officially last year: http://www.slate.com/blogs/future_tense/2014/11/21/no_license_needed_to_put_nintendo_characters_in_non_commercial_media_says.html
