### ISSUE TITLE
Adding different characters to each level?

### ISSUE THREAD

**Issue by mckenziedave** [MattSurabian/DuckHunt-JS#15]
Hi everyone,
Im trying to add different characters to different levels (so it isnt always the same two ducks) I have created different .png files and added them to the css however not sure where in the JS script to adjust the code? Im guessing I will need an if statment using each level ID.

this is where its picking up the ducks (duckA / B) in the JS
```
{var e=t%2===0?"duckA":"duckB";this.duckMax++,this.liveDucks.push(new Duck(this.duckMax.toString(),e,this.level.speed,this.playfield).fly())}},
killDuck:function(t){this.levelStats.ducksKilled+=1,this.liveDucks=_(this.liveDucks).reject(function(e){return e.id===t.id}),
0===this.liveDucks.length&&this.playfield.trigger("wave:end",this.curWave)},
drawDucks:function(){var t="",e=this.level.ducks*this.curWave-this.levelStats.ducksKilled;e=e>25?25:e;
```
And these are the Levels

```
levels=[
{id:1,title:"Level 1",waves:1,ducks:10,pointsPerDuck:100,speed:2,bullets:15,time:25},
{id:2,title:"Level 2",waves:1,ducks:10,pointsPerDuck:150,speed:4,bullets:15,time:20},
{id:3,title:"Level 3",waves:1,ducks:10,pointsPerDuck:200,speed:6,bullets:15,time:18}],
```
I want to be able to have duckC / D on level 2 (id 2) and duckE / F on level 3 (id 3).... Can anyone help?

**Comment by MattSurabian** [comment]
I'd love to help with this, but I have a few questions.

Is this part of a larger refactor/derivative work project that is already underway and is there anyway to hold off on development there for another week? I have a [branch with a larger refactor](https://github.com/MattSurabian/DuckHunt-JS/pull/14) that makes working with assets a whole lot easier and would make this task specifically very straightforward. The existing code in master is not very flexible with regards to this.

If you want to start playing around with the newer code, checkout this branch: https://github.com/MattSurabian/DuckHunt-JS/tree/pixi

And look at this chunk of code: https://github.com/MattSurabian/DuckHunt-JS/blob/pixi/src/modules/Stage.js#L141-L160 and this: https://github.com/MattSurabian/DuckHunt-JS/blob/pixi/src/modules/Game.js#L191

To accomplish what you're after I'd suggest modifying the `addDucks` to accept the character ID which could be added to the [level data](https://github.com/MattSurabian/DuckHunt-JS/blob/pixi/src/data/levels.json) and passed to the method, instead of (assigned in the method as it is now)[https://github.com/MattSurabian/DuckHunt-JS/blob/pixi/src/modules/Stage.js#L143].

I wouldn't recommend trying to make this work on the existing code base in master as within a week it will be officially deprecated.

**Comment by MattSurabian** [comment]
New duck type assets can be added here: https://github.com/MattSurabian/DuckHunt-JS/tree/pixi/src/assets/images/duck

**Comment by MattSurabian** [comment]
Based on #16 it sounds like you've got different characters working in each level. Feel free to reopen if you still have questions!
