### ISSUE TITLE
Cant get gulp dev to work

### ISSUE THREAD

**Issue by gonzad26** [MattSurabian/DuckHunt-JS#20]
Hi, i'm trying to make some little changes and i'm trying to use the command gulp dev, but it doesnt work. Throws the following error:

`[17:12:11] Using gulpfile ~/Downloads/DuckHunt-JS-master/gulpfile.js
[17:12:11] Starting 'images'...
[17:12:11] Starting 'audio'...
[17:12:11] Finished 'audio' after 33 ms
[17:12:11] Starting 'jshint'...
[17:12:11] Starting 'jscs'...
[17:12:12] Starting 'modules'...
[17:12:12] Finished 'modules' after 43 ms
[17:12:12] Starting 'watch'...
[17:12:12] Finished 'watch' after 104 ms
[17:12:12] Starting 'serve'...
[17:12:12] Finished 'serve' after 57 ms
[17:12:12] Server started http://localhost:8080
[17:12:12] LiveReload started on port 35729

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)`

Algo i had to install TexturePacker from a deb file because npm didnt install it.
Thanks

**Comment by MattSurabian** [comment]
It's true texture packer is a distinct dep, [the task should warn you](https://github.com/MattSurabian/DuckHunt-JS/blob/master/gulpfile.js#L82), did that happen?

I suspect this is an issue with texture packer causing the run to fail. 
 What happens if you remove texture packer from the task [here](https://github.com/MattSurabian/DuckHunt-JS/blob/master/gulpfile.js#L99)? 

Here's a version of the built sprite sheet so you can pre-populate `dist/` with it.

![sprites](https://cloud.githubusercontent.com/assets/1134260/13865030/3d05a7ba-ec7d-11e5-9b15-b197ebc7e87d.png)

Hopefully we can get to the bottom of this and fix it.

**Comment by gonzad26** [comment]
Hi, thanks for the quick answer. 

I figured out that I have to install texturepacker apart. Running the gulp dev command, it shows the exception that I put in the first message. 

When I tried with gulp images I saw that I need also texturr packer so I installed the corresponding deb file.

I get to build all if I run the gulp commands individually. The only one that works strange is gulp modules, it won't finish y have to press ctrl c to stop it.







From: Matthew Surabian

Sent: Thursday, March 17, 21:20

Subject: Re: [DuckHunt-JS] Cant get gulp dev to work (#20)

To: MattSurabian/DuckHunt-JS

Cc: Gonzalo Diaz



It's true texture packer is a distinct dep, the task should warn you, did that happen?


I suspect this is an issue with texture packer causing the run to fail. 

What happens if you remove texture packer from the task here? 


Here's a version of the built sprite sheet so you can pre-populate dist/ with it.





Hopefully we can get to the bottom of this and fix it.

**Comment by MattSurabian** [comment]
It looks like `gulp modules` is finishing based on the output you pasted above

```
[17:12:12] Starting 'modules'...
[17:12:12] Finished 'modules' after 43 ms
```

So you're saying `gulp images`, `gulp audio`, `gulp jshint`, `gulp jscs` work but `gulp dev` exits with the above error and `gulp modules` hangs?

**Comment by MattSurabian** [comment]
Any updates @gonzad26 or am I free to close this?

**Comment by gonzad26** [comment]
I've working with it because I have to work with another project, in two o three weeks I will resume working with it.
I will tell if there is any progress.
Thanks

**Comment by MattSurabian** [comment]
Thanks for replying, I definitely understand juggling multiple projects. I'm going to close this issue in the meantime only because no one else has chimed in with the same problem. Please don't hesitate to reopen it when you get a chance to work with this repo again if you run into trouble with `gulp dev`.
