### ISSUE TITLE
how to make two players 

### ISSUE THREAD

**Issue by arunmukrambi** [MattSurabian/DuckHunt-JS#31]
how to make two players game player1 should kill only red duck and player2 should kill black duck

**Comment by MattSurabian** [comment]
There are a few ways you could accomplish this. None are particularly "easy".

If you're talking about being able to share the same game session over the network you'd have to build some kind of lobby area to match-make in or you'd have to setup a new session URI for each game load and allow other folks who access that same URI to establish a WebRTC connection and play against each other that way. Either way you'd have to get deep into WebRTC.

The two player rule change you're suggesting (each player shooting a specific duck) wouldn't be too difficult to implement at all, just some additional logic in the `shotsFired` stage method https://github.com/MattSurabian/DuckHunt-JS/blob/master/src/modules/Stage.js#L186 Probably somewhere around here https://github.com/MattSurabian/DuckHunt-JS/blob/master/src/modules/Stage.js#L196

I don't want to discourage you from trying to make this a two player game; but you should know the reason it's not already a two player game is not because it's technically challenging, but because it would be expensive. I have some WebRTC experience and I've thought many times about setting up the game so two people could play; in order to do that I'd need to fund the continued operation of something called a WebRTC STUN/TURN server, this would not be a cheap undertaking. If you haven't worked with WebRTC before or don't want to learn, I'd forget about trying to make this two player and just take turns seeing who can get the highest score. To that end, doing a leader board and updating the difficulty of the existing levels is something I'll likely undertake at some point so folks can compete for high scores.

As far as a true two player experience goes, unless some company out there wants to give me free access to their TURN server don't expect this game to ever have two player mode. That said, it has been a while since WebRTC and this game first came out, maybe you can find a developer program with cheap or free access that includes a bandwidth cap or other restrictions and give it a try.

**Comment by arunmukrambi** [comment]
thank you sir for your response and one more i want to make count of killed red ducks and black ducks

**Comment by MattSurabian** [comment]
In that same `shotsFired` loop you just need to check `duck.options.colorProfile` to figure what color it is an increment a counter to match.

**Comment by arunmukrambi** [comment]
thank you i will try to solve

**Comment by arunmukrambi** [comment]
i tried to make change in colours but it is showing only one colour either
red nor black could you please help?

**Comment by MattSurabian** [comment]
Sorry arun, I can't. I suggest diving into the code some more and adding some console.log statements to help orient yourself. Good luck

**Comment by arunmukrambi** [comment]
ya ok thank you made easy for me thank you for response

**Comment by arunmukrambi** [comment]
hi is it possible to change birds images
